# Generated by Django 4.1.3 on 2022-11-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Mobile', models.PositiveIntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('Company_Name', models.CharField(max_length=15)),
                ('Currency', models.CharField(max_length=50)),
                ('Billing_method', models.CharField(max_length=50)),
                ('Profile_picture', models.FileField(upload_to='')),
            ],
        ),
    ]
